search_space:
#  uc_drop:
#    _type: uniform
#    _value: [0, 1]
#  alpha_uc:
#    _type: uniform
#    _value: [0, 1]
#  num_sample:
#    _type: randint
#    _value: [1, 100]
  clip_max_norm:
      _type: choice
      _value: [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1, 5, 10]


trial_command: PYTHONPATH=. python nni_experiment/rankingkd.py --dataset msvd --teacher_load=ckpt/msvd/msvd_a.pth --load=ckpt/msvd/msvd_b.pth --batch_size=6 --batch_size_val=32 --loss_func=stlistnet --neg_sampler=exp
trial_code_directory: ~/KD

trialGpuNumber: 1
trial_concurrency: 4
max_trial_number: 1000

tuner:
  name: TPE
  class_args:
    optimize_mode: maximize

training_service:
  platform: local
  useActiveGpu: True
  maxTrialNumberPerGpu: 1
  gpuIndices: 2,3,4,7