search_space:
  alpha0:
    _type: quniform
    _value: [ 0, 1, 0.01 ]
  alpha1:
    _type: randint
    _value: [ 5, 30 ]
  alpha2:
    _type: quniform
    _value: [ 0, 0.1, 0.01 ]
  warmup_alpha:
    _type: choice
    _value: [true, false]
  ft_last:
    _type: choice
    _value: [true, false]
  n_pos:
    _type: randint
    _value: [ 5, 30 ]
  n_neg:
    _type: quniform
    _value: [ 0, 500, 10 ]

trial_command: PYTHONPATH=. python nni_experiment/rankingkd.py --dataset msvd --batch_size=6 --batch_size_val=32
trial_code_directory: ~/KD

trialGpuNumber: 1
trial_concurrency: 4
max_trial_number: 1000

tuner:
  name: TPE
  class_args:
    optimize_mode: maximize

training_service:
  platform: local
  useActiveGpu: True
  maxTrialNumberPerGpu: 1