search_space:
  alpha_v:
      _type: choice
      _value: [0, 0.1, 0.5, 1, 5, 10, 15]
  alpha_f:
    _type: choice
    _value: [ 0, 0.001, 0.01, 0.1, 1, 5 ]


trial_command: PYTHONPATH=. python rankingkd.py --dataset msvd --teacher_load=ckpt/msvd/msvd_a.pth --load=ckpt/msvd/msvd_b.pth --batch_size=6 --batch_size_val=32 --loss_func=stlistnet --neg_sampler=exp
trial_code_directory: ~/KD

trialGpuNumber: 1
trial_concurrency: 2
max_trial_number: 1000

tuner:
  name: TPE
  class_args:
    optimize_mode: maximize

training_service:
  platform: local
  useActiveGpu: True
  maxTrialNumberPerGpu: 1
  gpuIndices: 0, 1