search_space:
  uc_at:
    _type: choice
    _value: ['b', 'm', 'l']
  uc_drop:
    _type: uniform
    _value: [0, 1]
  alpha_uc:
    _type: uniform
    _value: [0, 1]
  lr:
    _type: uniform
    _value: [0.00001, 0.0001]
  num_sample:
    _type: randint
    _value: [1, 100]


trial_command: PYTHONPATH=. python nni_experiment/rankingkd.py --dataset msvd --teacher_load=ckpt/msvd/msvd_a.pth --load=ckpt/msvd/msvd_b.pth --batch_size=6 --batch_size_val=32 --loss_func=stlistnet --neg_sampler=exp
trial_code_directory: ~/KD

trialGpuNumber: 1
trial_concurrency: 4
max_trial_number: 1000

tuner:
  name: TPE
  class_args:
    optimize_mode: maximize

training_service:
  platform: local
  useActiveGpu: True
  maxTrialNumberPerGpu: 1
  gpuIndices: 0,2,3,4,7